/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/hhe/Downloads/husseinlopol.glb --transform --simplify --bones 
Files: /Users/hhe/Downloads/husseinlopol.glb [72.03MB] > /Users/hhe/husseinlopol-transformed.glb [2.88MB] (96%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/husseinlopol-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} name="mixamorigHips" position={[0.238, -1.858, 21.794]} rotation={[-1.617, 0.001, -0.026]}>
            <primitive object={nodes.mixamorigSpine} name="mixamorigSpine" position={[-0.02, 6.728, 0.129]} rotation={[0.023, -0.003, -0.006]}>
              <primitive object={nodes.mixamorigSpine1} name="mixamorigSpine1" position={[-0.001, 7.446, -0.128]} rotation={[0.02, 0.005, 0.054]}>
                <primitive object={nodes.mixamorigSpine2} name="mixamorigSpine2" position={[0.19, 9.019, 0.088]} rotation={[-0.007, -0.002, 0.022]}>
                  <primitive object={nodes.mixamorigNeck} name="mixamorigNeck" position={[0.298, 11.016, -0.409]} rotation={[-0.151, -0.018, 0.112]}>
                    <primitive object={nodes.mixamorigHead} name="mixamorigHead" position={[0.212, 3.447, 0.644]} rotation={[0.168, -0.001, -0.155]} />
                  </primitive>
                  <primitive object={nodes.mixamorigLeftShoulder} name="mixamorigLeftShoulder" position={[6.51, 9.587, -0.402]} rotation={[1.578, -0.399, -1.596]}>
                    <primitive object={nodes.mixamorigLeftArm} name="mixamorigLeftArm" position={[0.492, 11.968, -1.368]} rotation={[-0.205, -0.017, -0.069]}>
                      <primitive object={nodes.mixamorigLeftForeArm} name="mixamorigLeftForeArm" position={[0.314, 8.569, -0.154]} rotation={[-0.001, 0.022, 0.143]}>
                        <primitive object={nodes.mixamorigLeftHand} name="mixamorigLeftHand" position={[0.435, 12.842, -1.9]} rotation={[0.028, 0.005, 0.04]} />
                      </primitive>
                    </primitive>
                  </primitive>
                  <primitive object={nodes.mixamorigRightShoulder} name="mixamorigRightShoulder" position={[-6.236, 9.988, -0.258]} rotation={[1.578, 0.33, 1.594]}>
                    <primitive object={nodes.mixamorigRightArm} name="mixamorigRightArm" position={[-0.371, 11.696, -1.144]} rotation={[-0.157, 0.01, 0.017]}>
                      <primitive object={nodes.mixamorigRightForeArm} name="mixamorigRightForeArm" position={[-0.603, 8.684, -0.891]} rotation={[-0.024, -0.033, -0.169]}>
                        <primitive object={nodes.mixamorigRightHand} name="mixamorigRightHand" position={[-1.297, 12.669, -2.089]} rotation={[-0.037, 0, -0.005]} />
                      </primitive>
                    </primitive>
                  </primitive>
                </primitive>
              </primitive>
            </primitive>
            <primitive object={nodes.mixamorigLeftUpLeg} name="mixamorigLeftUpLeg" position={[8.284, -2.976, -0.392]} rotation={[0.041, 0.002, -3.057]}>
              <primitive object={nodes.mixamorigLeftLeg} name="mixamorigLeftLeg" position={[-0.097, 14.787, -0.114]} rotation={[-0.055, 0.009, 0.001]}>
                <primitive object={nodes.mixamorigLeftFoot} name="mixamorigLeftFoot" position={[-0.044, 10.176, -0.174]} rotation={[1.024, -0.048, 0.188]}>
                  <primitive object={nodes.mixamorigLeftToeBase} name="mixamorigLeftToeBase" position={[0.186, 11.373, -0.178]} rotation={[0.593, -0.127, 0.013]} />
                </primitive>
              </primitive>
            </primitive>
            <primitive object={nodes.mixamorigRightUpLeg} name="mixamorigRightUpLeg" position={[-7.867, -3.554, -0.399]} rotation={[0.04, -0.004, 3.075]}>
              <primitive object={nodes.mixamorigRightLeg} name="mixamorigRightLeg" position={[0.105, 14.636, 0.004]} rotation={[-0.104, -0.014, 0.06]}>
                <primitive object={nodes.mixamorigRightFoot} name="mixamorigRightFoot" position={[0.342, 9.817, -0.237]} rotation={[1.042, 0.031, -0.196]}>
                  <primitive object={nodes.mixamorigRightToeBase} name="mixamorigRightToeBase" position={[0.438, 11.953, -0.21]} rotation={[0.651, 0.124, -0.158]} />
                </primitive>
              </primitive>
            </primitive>
          </primitive>
        </group>
        <skinnedMesh name="mesh" geometry={nodes.mesh.geometry} material={materials['Material.001']} skeleton={nodes.mesh.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/husseinlopol-transformed.glb')
